### PR TITLE
Much cooler music

### PR DESCRIPTION
**Pull request by secretrobotron**
Working on new music integration:
- [x] Add new layers
- [x] Add intro music song
- [x] Get lengthened layers from @DevonBird 
- [x] Get reverb tail start positions from @DevonBird 
- [x] Add song switching to accommodate menu music, or just add simple music to the menu through sound engine
- [x] Add ability to transition between intro music and gameplay loop
- [x] Add intensity meter with thresholds for layers that smoothly transitions between them
- [x] Fix menu music (it doesn't loop properly anymore for some reason yay)

### CODE REVIEW

**Comment by secretrobotron** [comment]
@DevonBird @flukeout I think we're going to have trouble with the switch from the menu to the game, because it's an actual html page switch. Like, it reloads the javascript engine between them. @flukeout this would be an excuse to meld the two together if you still want to try. Or, @DevonBird we can come up with a clean fade-out or something from the menu. The way we have it set up right now, there's a necessary break in sound between the menu and the game (I *think*).

**Comment by flukeout** [comment]
@DevonBird @secretrobotron yeah, I flagged that earlier as a consideration for the music. Does the system you guys came up with depend on seamless transitions? It would be a lot easier if we were able to fade out and back in. We could come up with some way around this, but it would involve refactoring a bunch of stuff. Might be a good post-launch feature?

**Comment by flukeout** [comment]
@secretrobotron hey man, tested this out and wanted to confirm that I was hearing what I was supposed to..

* Rules, Splash -> no music
* Gameplay -> base layer backing track with a few drum fills once in a while, according to the console, seemed to be looping every once in a while

I never heard any of the melody from the previous track, was it supposed to come on at some point or be triggered by something?

The music also sounds really quiet relative to the sound effects at this point, is that your experience too? I know its still a WIP so just wanted to make sure that that's what is expected at this point.

Sweet.

**Comment by secretrobotron** [comment]
@DevonBird The "round start" chime conflicts a lot with the music. I wonder if we could do something like add a special layer that's just for the round starting... Or something. I don't know.

**Comment by secretrobotron** [comment]
@DevonBird also, after playing with it a bit, I've noticed that the 3rd layer with the cool synths is really the "OH MAN! This is intense!" barrier. When that layers turns on, it's really obvious and cool. But, I don't think that layer has a lot in it, so sometimes when you cross that intensity threshold, you don't hear anything until the synths come in in the song. Does that make sense? In other words, it might be good to have that layer be more consistent, like just cool synths more often, so that regardless of where the song is, you'll hear those synths if the intensity level gets there.

**Comment by secretrobotron** [comment]
@flukeout thanks man. Working a bit slower to get some of the engine stuff right. I'll put music into the menus and stuff next.

But! The rest is working pretty well now, I think. Try playing the game a bit on this branch. If you smash the ball a few times, the intensity will get up high enough to play the other layers of the song. I think it works pretty well :).

I also fixed a couple of problems where the sound engine wasn't hooked up just right, so it should work a bit better at the end of rounds and stuff now. e.g. the music gets quiet when you're in the "FINISH HIM" part. @DevonBird it made me curious: do we want to adjust the music in another way here?

**Pull request merged**
