### PR TITLE
Analog switching

### PR DESCRIPTION
**Pull request by secretrobotron**
- [x] need to smooth out angle of paddle using `targetAngle` being mindful of `atan2` crossover :/

### CODE REVIEW

**Comment by secretrobotron** [comment]
@flukeout this works now with proper smoothing for the paddle.

I added something ugly to the splash screen to let people pick which controller setup they want to use. What's a better way to specify it? Maybe we can just remove it altogether and keep it as a debug option for when we're playtesting.

**Comment by secretrobotron** [comment]
Worst pull request ever.

**Comment by flukeout** [comment]
But keep the analog stuff!

**Comment by flukeout** [comment]
the good parts

**Pull request closed without merging**
