### PR TITLE
[WIP] - Dash updates

### PR DESCRIPTION
**Pull request by flukeout**
This adds the ability to move slightly while the dash phase is cooling down while using the joystick.

### CODE REVIEW

**Comment by flukeout** [comment]
Hey @secretrobotron try this out, it sets the paddle velocity to 0 right before a dash so you get the full force of the dash no matter which way you are moving or pointing. See if this feels any better to you. It has some quirks still where if you are moving up and then do a side-dash you dash way faster than you should considering it's a `broad face` dash.

**Comment by flukeout** [comment]
You can ignore that wall of text, I made it so when you dash, the speed of the dash is based on where you want to dash to vs which way the paddle is oriented (instead of comparing the current paddle velocity to where it is orientated). Do try it though.

**Comment by secretrobotron** [comment]
Hey, this is great. I'm finding it a lot easier to get gun shots when dashing now too, which is cool.

**Comment by flukeout** [comment]
Closing as dashing is dead. Long live the next idea.

**Pull request closed without merging**
