### PR TITLE
Planet graphics & Paddle Dash

### LINKED ISSUE #77: Board doesn't tilt anymore
No more tilting when you move around

### PR DESCRIPTION
**Pull request by flukeout**
Still a work in progress, but let's merge if it works and I can keep updating it. Should look something like...

image

Also fixes #77 (restores board tilting)

**Notes**—this breaks a few of the effects that relied on changing the background color of the board as well as when the ball breaks through the wall at the end of a round. I'll have to update those.

### CODE REVIEW

**Comment by secretrobotron** [comment]
It looks *great*. TBH, I don't notice the couple of effects you said are broken.

It's making my machine way hotter than before though. I tried disabling the moon animations, but it didn't make much of a difference. A slowdown for the big effects (particle+board shift) when you score is really noticeable now. I'm curious about whether SVGs make it more of a problem than JPGs or PNGs (I would wager not).

**Comment by flukeout** [comment]
@secretrobotron Are you able to just comment out each piece of the `.scene` markup to see if you can return to the old performance you were getting? Only the moons have any kind of animation attached to them.

**Comment by flukeout** [comment]
Progress update. Working on a wider moonscape that we can move/rotate underneath the playing board to match the terrain percentages.

Screengrab...
image

**Comment by secretrobotron** [comment]
screenshot 2017-12-07 01 19 27

💀

**Comment by secretrobotron** [comment]
@flukeout 

> Are you able to just comment out each piece of the .scene markup to see if you can return to the old performance you were getting? Only the moons have any kind of animation attached to them.

Yeah, I'll do some real testing with it.

**Comment by flukeout** [comment]
Cool @secretrobotron—let me know what you find, let's keep this PR open as I update the graphics.

**Comment by flukeout** [comment]
Latest progress...

image

**Comment by flukeout** [comment]
DId you get a chance to test performance @secretrobotron

**Comment by secretrobotron** [comment]
@flukeout some thoughts here:

* runs smooth like a penguin on an ice slide in Chrome
* i really like the texture on the planet surface, but the motion of it is lost in the action of the game, and redundant with the field of play
  * it might actually help for it to occupy less of the screen. right now it's pretty dominant
  * the purple vs green thing is already really apparent on the board
* what might work better is having a neutral colour for the planet
  * maybe actions can happen on the planet surface that mirror action in the field of play
  * e.g. when purple scores, a green ship flies by and gets shot down
  * the planet could rotate constantly, perhaps, and show ongoing purple vs green battle on its surface through little explosions or something
* in fact, we could do away with the planet altogether and instead have some of the fragments you created fly by in the background. maybe on an asteroid or something so we can reuse the assets you made
* would you be able to make a few more frames of animation for the big yellow moon so that it could turn around and show a face of appreciation or dismay at important moments?

**Comment by secretrobotron** [comment]
* another though: the planet surface could be what spawns the powerups. like, the get shot up to the board from the planet below or something.

**Comment by secretrobotron** [comment]
Playing around with opacity ideas:
screenshot 2017-12-08 23 28 10

**Comment by secretrobotron** [comment]
Zooming out helps a bit too: https://giphy.com/gifs/xT0xeBAVEyB1aOisPC (also a cool "take off into space" effect)

**Comment by secretrobotron** [comment]
explosions

**Comment by ryanwarsaw** [comment]
The amount of stuff going on in that gif is just insane! 😱

**Comment by flukeout** [comment]
Yo, dude—super sweet stuff and ideas.

* I agree that the two-tone planet isn't working.
  * I'm going to try to make it a neutral color.
  * Moving the planet under the board gets kind of dizzying, we can try some more subtle like up and down motions to suggest floating etc, but rotating it made me get queasy when I tried it before
* Love the zoom out effect in the planet at start of the match / round
* 👍 to the idea of adding effects to the terrain (both planet and moon in the back) to correspond to game actions
  * For example, i want to try to light up the eyes of the little robot planet to match the color of the player that scored
  * I like the volcano effects you added and like the concept of making them shoot the powerups, I'll try that
  * We could also move a planet to the left or right depending on the rounds won, or maybe add little planets as indicators of your score...
* While the opacity looks pretty sweet, I'm wary of it because it sort of changes the whole particles and board control effect, so I want to try to keep it as is with a neutral planet underneath.
  * Fuck it looks cool though so I'm torn.

**Comment by secretrobotron** [comment]
The dithering in the gif makes me think it could be a good substitute for the green/purple on the board. It's enough texture to help you focus on the board, I think.

> While the opacity looks pretty sweet, I'm wary of it because it sort of changes the whole particles and board control effect, so I want to try to keep it as is with a neutral planet underneath. 

Hahaha I know. It still comes across though, right? The low opacity lets you see the cool scenery down below.

> For example, i want to try to light up the eyes of the little robot planet to match the color of the player that scored

That's an amazing idea.

> We could also move a planet to the left or right depending on the rounds won, or maybe add little planets as indicators of your score...

We could perhaps come up with a few goofy things that could happen on the moon surface. Like, a green spaceship lands and puts out a flag. It could get progessively more colonized, and when the other player scores, some of their colony explodes? Hahah aahahhhhhhhh...

**Comment by secretrobotron** [comment]
> Moving the planet under the board gets kind of dizzying, we can try some more subtle like up and down motions to suggest floating etc, but rotating it made me get queasy when I tried it before

Constant motion, you mean? Just left -> right?

**Comment by flukeout** [comment]
> Constant motion, you mean? Just left -> right?

Even just the motion as it rotates to keep track of the board state. I found it kind of distracting when the ball is moving one way and the planet the other.

Anyway let's hop on a call soon and discuss. Lots of cool options we should explore.

**Comment by secretrobotron** [comment]
> Again, easier to chat in person, so let's find some time soon.

👍 I know you're busy now. Lemme know when you have some downtime.

> I think just looking at the very first image I posted in this thread, i feel like its quite pleasing. I think the changes I've been introducing kind of take it away from that simplicity.

Yeah, i do like the solid purple underneath the board. But, I wouldn't get rid of the detail you added to the other two floating bodies. I think just we just need to get rid of the idea of the surface as another metaphor for who's winning.

**Comment by flukeout** [comment]
@secretrobotron Please ping me on whatsapp or here when you start working on this. I'm going to commit a few more minor things but don't want to do it if you've already started.

**Comment by secretrobotron** [comment]
Rebased and merged in with #85 !

**Pull request closed without merging**
