### PR TITLE
Better Electron Packaging

### PR DESCRIPTION
**Pull request by secretrobotron**
electron-forge is cool n' all, but it's also a bit annoying. It requires that everything be in a specific folder structure, and this project isn't exactly conventional in its setup. Anyway, here's some cool stuff that's fixed/implemented:

1. Silly fix for framerate.js.
2. Add build/ to gitignore.
3. Move electron stuff to an electron folder.
4. Take electron parts of package.json and put them in a specific package.json *just* for the electron build
5. Use gulp to copy everything important into a build folder with a specific layout so that electron won't complain (geeze).
6. Some string manipulation for index.html so that it can just load the minified version of the code.
7. Code minification!

### CODE REVIEW

**Comment by secretrobotron** [comment]
@flukeout just want to give you a heads up that this will land. It doesn't change anything further about the code layout, but tries to do the electron build in a slightly better way. Like this, we can tell electron-forge just to package the minified version of the code—not the entire source tree (super helpful, thanks electron-forge 🤦‍♀️ ).

**Comment by ryanwarsaw** [comment]
You could rig this up to Travis CI and have it automatically build packaged apps and deploy them to Github releases or S3, that's what I did with Jisort 😉

**Comment by secretrobotron** [comment]
Thanks @ryanwarsaw . Do you have any experience with Electron? Hasn't been the easiest thing to cajole.

**Comment by ryanwarsaw** [comment]
Just with fixing bugs in relation with it, mostly performance or distribution stuff. I'm super excited to see you guys are rolling it out for battle pong though 🎉

**Pull request merged**
