### PR TITLE
wip perf checkup with disable settings

### PR DESCRIPTION
**Pull request by secretrobotron**
@flukeout if you get a chance to look at this a bit, I'd appreciate doing some paired hunting. I'm trying to snip out things that are potentially performance-hungry, or put them behind an option in `Settings`. (e.g. [here](https://github.com/secretrobotron/games/compare/perf-checkup?expand=1#diff-2c7ba005fd0bbd49e4f673d428ab4558R20)).

The thing that makes the biggest difference on my system is the animations. Forcing them all to stop is really helpful.

One thing I could use your help on is fixing the terrain in this branch. I used `transform: scale` instead of width because I think that causes a huge reflow. It made me look at the html a bit, and I noticed that there is some font and stuff inside those terrain elements to say "best of ...". Can we lift them out onto another layer that doesn't have transform/animation? It *might* help a bit more.

### CODE REVIEW

**Comment by flukeout** [comment]
Yeah, let's jump on a call about this stuff sometime. There's a lot of moving parts so would be cool to see what you've found and what we can optimize.

**Comment by flukeout** [comment]
One idea is to try to automatically adjust the effects in the game based on the average framerate we are seeing. We could just have a list of things we turn off one by one if the framerate is too low for like a 5 second stretch etc. I have a suspicion, curious if you've checked, that just the general planet and moon bobbing animations are a drain.

**Comment by flukeout** [comment]
A good place to start could be the splash page, that thing alone makes my fans spin crazy!

**Comment by flukeout** [comment]
I refactored the terrain sizes so that they are now working via transforms instead of width and moved the score text elements outta them.

**Comment by secretrobotron** [comment]
> I refactored the terrain sizes so that they are now working via transforms instead of width and moved the score text elements outta them.

That's awesome. I think removing the text from them will help a lot.

Where are you doing this work? Not in this pull request, right?

**Comment by flukeout** [comment]
Thanks for contributing to open source. You are valued and appreciated @secretrobotron

**Comment by flukeout** [comment]
NOTE: WILL NEVER MERGE THIS

**Comment by flukeout** [comment]
Thank you though!

**Pull request closed without merging**
