### PR TITLE
Objet editeur

### PR DESCRIPTION
**Pull request by secretrobotron**
Obje**C**t editor

Does a bunch of useful things:

* Uses individually written animation definitions
* Uses an object model to load/store objects that animate according to different states

### CODE REVIEW

**Comment by secretrobotron** [comment]
@flukeout this really closely resembles your editor, but with a few structural changes to let us make games piece-wise a bit easier.

**Comment by flukeout** [comment]
``Does a bunch of useful things:`` <- one of these words is up for debate

**Comment by secretrobotron** [comment]
> one of these words is up for debate

"Does"

**Comment by flukeout** [comment]
"Anti-Matter: Does a bunch of useful."

**Pull request merged**
