### PR TITLE
Code and assets for reactions to winning/losing

### PR DESCRIPTION
**Pull request by secretrobotron**

### CODE REVIEW

**Comment by ryanwarsaw** [comment]
This is really cool :D

**Comment by secretrobotron** [comment]
New & improved.

**Comment by ryanwarsaw** [comment]
SVGs could probably benefit from some optimization 😉

**Comment by secretrobotron** [comment]
@ryanwarsaw yeah, good suggestion. I tried the font, but browser support seems weak. What do you recommend for crunching those svgs?

**Pull request merged**
